### ISSUE TITLE
Nothing happen

### ISSUE THREAD

**Issue by rochapablo** [marc1404/gulp-blueprint-babel#1]
Here's what I tried:

```
var babel = require('gulp-blueprint-babel');

gulp.task('js', function() {
  console.log('js task');
});

gulp.task("production", function() {
gulp.src(files.app.concat(files.build, files.views))
    gulp.src(files.app.concat(files.build, files.views))
    .pipe(concat("script.js"))
    //.pipe(babel())
    .pipe(gulp.dest("./public/assets/js"));
});

babel({
  'gulp': gulp,
  'basedir': './public/assets/js',
  'input': 'script.js',
  'output': 'script.js',
  'dest': './public/assets/js'
});
```

**Comment by marc1404** [comment]
The module is not intended to be included in a gulp stream.
Instead you should only call `babel()` which will setup your task.
I should mention that I do not longer maintain this module but thank you for opening up an issue!
Personally, I can recommend looking at Laravel Elixir (https://www.npmjs.com/package/laravel-elixir) which helps me to setup a working gulp build pretty quickly.

**Comment by rochapablo** [comment]
That's OK, I'll check that.

Thank you for your time.
